--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2026-10-05 23:18:43

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 223 (class 1259 OID 66189)
-- Name: Courses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Courses" (
    "Id" integer NOT NULL,
    "Name" character varying(120) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "Credits" integer NOT NULL,
    "TeacherId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Courses" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 66188)
-- Name: Courses_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Courses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Courses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 66202)
-- Name: Enrollments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Enrollments" (
    "Id" integer NOT NULL,
    "StudentId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    "EnrollmentDate" timestamp with time zone NOT NULL,
    "Grade" numeric(5,2)
);


ALTER TABLE public."Enrollments" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 66201)
-- Name: Enrollments_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Enrollments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Enrollments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 66177)
-- Name: Students; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Students" (
    "Id" integer NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "Email" character varying(120) NOT NULL,
    "BirthDate" timestamp without time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Students" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 66176)
-- Name: Students_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Students" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Students_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 66183)
-- Name: Teachers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Teachers" (
    "Id" integer NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "Email" character varying(120) NOT NULL,
    "Department" character varying(100) NOT NULL
);


ALTER TABLE public."Teachers" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 66182)
-- Name: Teachers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Teachers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Teachers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 66171)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4883 (class 0 OID 66189)
-- Dependencies: 223
-- Data for Name: Courses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Courses" ("Id", "Name", "Description", "Credits", "TeacherId", "CreatedAt") FROM stdin;
1	Web Development	Основы разработки веб-приложений	5	1	2026-10-05 16:54:52.242818+05
\.


--
-- TOC entry 4885 (class 0 OID 66202)
-- Dependencies: 225
-- Data for Name: Enrollments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Enrollments" ("Id", "StudentId", "CourseId", "EnrollmentDate", "Grade") FROM stdin;
1	1	1	2026-10-05 17:17:21.073409+05	\N
\.


--
-- TOC entry 4879 (class 0 OID 66177)
-- Dependencies: 219
-- Data for Name: Students; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Students" ("Id", "FirstName", "LastName", "Email", "BirthDate", "CreatedAt") FROM stdin;
1	Иван	Петров	ivan.petrov@example.com	2003-05-15 00:00:00	2026-10-05 16:48:26.174202+05
2	Анна	Сидорова	anna.sidorova@example.com	2004-08-20 00:00:00	2026-10-05 16:52:04.950405+05
\.


--
-- TOC entry 4881 (class 0 OID 66183)
-- Dependencies: 221
-- Data for Name: Teachers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Teachers" ("Id", "FirstName", "LastName", "Email", "Department") FROM stdin;
1	Алексей	Иванов	alexey.ivanov@example.com	Computer Science
\.


--
-- TOC entry 4877 (class 0 OID 66171)
-- Dependencies: 217
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20261004135158_InitialCreate	8.0.8
20261005114719_FixBirthDate	8.0.8
\.


--
-- TOC entry 4891 (class 0 OID 0)
-- Dependencies: 222
-- Name: Courses_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Courses_Id_seq"', 1, true);


--
-- TOC entry 4892 (class 0 OID 0)
-- Dependencies: 224
-- Name: Enrollments_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Enrollments_Id_seq"', 1, true);


--
-- TOC entry 4893 (class 0 OID 0)
-- Dependencies: 218
-- Name: Students_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Students_Id_seq"', 3, true);


--
-- TOC entry 4894 (class 0 OID 0)
-- Dependencies: 220
-- Name: Teachers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Teachers_Id_seq"', 1, true);


--
-- TOC entry 4724 (class 2606 OID 66195)
-- Name: Courses PK_Courses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Courses"
    ADD CONSTRAINT "PK_Courses" PRIMARY KEY ("Id");


--
-- TOC entry 4728 (class 2606 OID 66206)
-- Name: Enrollments PK_Enrollments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Enrollments"
    ADD CONSTRAINT "PK_Enrollments" PRIMARY KEY ("Id");


--
-- TOC entry 4718 (class 2606 OID 66181)
-- Name: Students PK_Students; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Students"
    ADD CONSTRAINT "PK_Students" PRIMARY KEY ("Id");


--
-- TOC entry 4721 (class 2606 OID 66187)
-- Name: Teachers PK_Teachers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Teachers"
    ADD CONSTRAINT "PK_Teachers" PRIMARY KEY ("Id");


--
-- TOC entry 4715 (class 2606 OID 66175)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4722 (class 1259 OID 66217)
-- Name: IX_Courses_TeacherId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Courses_TeacherId" ON public."Courses" USING btree ("TeacherId");


--
-- TOC entry 4725 (class 1259 OID 66218)
-- Name: IX_Enrollments_CourseId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Enrollments_CourseId" ON public."Enrollments" USING btree ("CourseId");


--
-- TOC entry 4726 (class 1259 OID 66219)
-- Name: IX_Enrollments_StudentId_CourseId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Enrollments_StudentId_CourseId" ON public."Enrollments" USING btree ("StudentId", "CourseId");


--
-- TOC entry 4716 (class 1259 OID 66220)
-- Name: IX_Students_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Students_Email" ON public."Students" USING btree ("Email");


--
-- TOC entry 4719 (class 1259 OID 66221)
-- Name: IX_Teachers_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Teachers_Email" ON public."Teachers" USING btree ("Email");


--
-- TOC entry 4729 (class 2606 OID 66196)
-- Name: Courses FK_Courses_Teachers_TeacherId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Courses"
    ADD CONSTRAINT "FK_Courses_Teachers_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES public."Teachers"("Id") ON DELETE RESTRICT;


--
-- TOC entry 4730 (class 2606 OID 66207)
-- Name: Enrollments FK_Enrollments_Courses_CourseId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Enrollments"
    ADD CONSTRAINT "FK_Enrollments_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES public."Courses"("Id") ON DELETE CASCADE;


--
-- TOC entry 4731 (class 2606 OID 66212)
-- Name: Enrollments FK_Enrollments_Students_StudentId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Enrollments"
    ADD CONSTRAINT "FK_Enrollments_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES public."Students"("Id") ON DELETE CASCADE;


-- Completed on 2026-10-05 23:18:45

--
-- PostgreSQL database dump complete
--

